// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/v1/agent.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ToteAgent_PrepareExport_FullMethodName = "/tote.v1.ToteAgent/PrepareExport"
	ToteAgent_ExportImage_FullMethodName   = "/tote.v1.ToteAgent/ExportImage"
	ToteAgent_ImportFrom_FullMethodName    = "/tote.v1.ToteAgent/ImportFrom"
	ToteAgent_ListImages_FullMethodName    = "/tote.v1.ToteAgent/ListImages"
	ToteAgent_ResolveTag_FullMethodName    = "/tote.v1.ToteAgent/ResolveTag"
)

// ToteAgentClient is the client API for ToteAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ToteAgentClient interface {
	// Controller -> agent: verify digest exists locally, register session.
	PrepareExport(ctx context.Context, in *PrepareExportRequest, opts ...grpc.CallOption) (*PrepareExportResponse, error)
	// Target agent -> source agent: stream image tar (authorized by session).
	ExportImage(ctx context.Context, in *ExportImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error)
	// Controller -> target agent: import image from source agent endpoint.
	ImportFrom(ctx context.Context, in *ImportFromRequest, opts ...grpc.CallOption) (*ImportFromResponse, error)
	// Controller -> agent: list local image digests.
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	// Controller -> agent: resolve a tag reference to a digest via containerd.
	ResolveTag(ctx context.Context, in *ResolveTagRequest, opts ...grpc.CallOption) (*ResolveTagResponse, error)
}

type toteAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewToteAgentClient(cc grpc.ClientConnInterface) ToteAgentClient {
	return &toteAgentClient{cc}
}

func (c *toteAgentClient) PrepareExport(ctx context.Context, in *PrepareExportRequest, opts ...grpc.CallOption) (*PrepareExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareExportResponse)
	err := c.cc.Invoke(ctx, ToteAgent_PrepareExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toteAgentClient) ExportImage(ctx context.Context, in *ExportImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ToteAgent_ServiceDesc.Streams[0], ToteAgent_ExportImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportImageRequest, DataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToteAgent_ExportImageClient = grpc.ServerStreamingClient[DataChunk]

func (c *toteAgentClient) ImportFrom(ctx context.Context, in *ImportFromRequest, opts ...grpc.CallOption) (*ImportFromResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportFromResponse)
	err := c.cc.Invoke(ctx, ToteAgent_ImportFrom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toteAgentClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, ToteAgent_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toteAgentClient) ResolveTag(ctx context.Context, in *ResolveTagRequest, opts ...grpc.CallOption) (*ResolveTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveTagResponse)
	err := c.cc.Invoke(ctx, ToteAgent_ResolveTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToteAgentServer is the server API for ToteAgent service.
// All implementations must embed UnimplementedToteAgentServer
// for forward compatibility.
type ToteAgentServer interface {
	// Controller -> agent: verify digest exists locally, register session.
	PrepareExport(context.Context, *PrepareExportRequest) (*PrepareExportResponse, error)
	// Target agent -> source agent: stream image tar (authorized by session).
	ExportImage(*ExportImageRequest, grpc.ServerStreamingServer[DataChunk]) error
	// Controller -> target agent: import image from source agent endpoint.
	ImportFrom(context.Context, *ImportFromRequest) (*ImportFromResponse, error)
	// Controller -> agent: list local image digests.
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	// Controller -> agent: resolve a tag reference to a digest via containerd.
	ResolveTag(context.Context, *ResolveTagRequest) (*ResolveTagResponse, error)
	mustEmbedUnimplementedToteAgentServer()
}

// UnimplementedToteAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToteAgentServer struct{}

func (UnimplementedToteAgentServer) PrepareExport(context.Context, *PrepareExportRequest) (*PrepareExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareExport not implemented")
}
func (UnimplementedToteAgentServer) ExportImage(*ExportImageRequest, grpc.ServerStreamingServer[DataChunk]) error {
	return status.Error(codes.Unimplemented, "method ExportImage not implemented")
}
func (UnimplementedToteAgentServer) ImportFrom(context.Context, *ImportFromRequest) (*ImportFromResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportFrom not implemented")
}
func (UnimplementedToteAgentServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedToteAgentServer) ResolveTag(context.Context, *ResolveTagRequest) (*ResolveTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveTag not implemented")
}
func (UnimplementedToteAgentServer) mustEmbedUnimplementedToteAgentServer() {}
func (UnimplementedToteAgentServer) testEmbeddedByValue()                   {}

// UnsafeToteAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToteAgentServer will
// result in compilation errors.
type UnsafeToteAgentServer interface {
	mustEmbedUnimplementedToteAgentServer()
}

func RegisterToteAgentServer(s grpc.ServiceRegistrar, srv ToteAgentServer) {
	// If the following call panics, it indicates UnimplementedToteAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToteAgent_ServiceDesc, srv)
}

func _ToteAgent_PrepareExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToteAgentServer).PrepareExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToteAgent_PrepareExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToteAgentServer).PrepareExport(ctx, req.(*PrepareExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToteAgent_ExportImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ToteAgentServer).ExportImage(m, &grpc.GenericServerStream[ExportImageRequest, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToteAgent_ExportImageServer = grpc.ServerStreamingServer[DataChunk]

func _ToteAgent_ImportFrom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportFromRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToteAgentServer).ImportFrom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToteAgent_ImportFrom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToteAgentServer).ImportFrom(ctx, req.(*ImportFromRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToteAgent_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToteAgentServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToteAgent_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToteAgentServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToteAgent_ResolveTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToteAgentServer).ResolveTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToteAgent_ResolveTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToteAgentServer).ResolveTag(ctx, req.(*ResolveTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToteAgent_ServiceDesc is the grpc.ServiceDesc for ToteAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToteAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tote.v1.ToteAgent",
	HandlerType: (*ToteAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareExport",
			Handler:    _ToteAgent_PrepareExport_Handler,
		},
		{
			MethodName: "ImportFrom",
			Handler:    _ToteAgent_ImportFrom_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _ToteAgent_ListImages_Handler,
		},
		{
			MethodName: "ResolveTag",
			Handler:    _ToteAgent_ResolveTag_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExportImage",
			Handler:       _ToteAgent_ExportImage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/agent.proto",
}
