// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/v1/agent.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareExportRequest) Reset() {
	*x = PrepareExportRequest{}
	mi := &file_api_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareExportRequest) ProtoMessage() {}

func (x *PrepareExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareExportRequest.ProtoReflect.Descriptor instead.
func (*PrepareExportRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareExportRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *PrepareExportRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type PrepareExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SizeBytes     int64                  `protobuf:"varint,1,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareExportResponse) Reset() {
	*x = PrepareExportResponse{}
	mi := &file_api_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareExportResponse) ProtoMessage() {}

func (x *PrepareExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareExportResponse.ProtoReflect.Descriptor instead.
func (*PrepareExportResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareExportResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type ExportImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportImageRequest) Reset() {
	*x = ExportImageRequest{}
	mi := &file_api_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportImageRequest) ProtoMessage() {}

func (x *ExportImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportImageRequest.ProtoReflect.Descriptor instead.
func (*ExportImageRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ExportImageRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type DataChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataChunk) Reset() {
	*x = DataChunk{}
	mi := &file_api_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChunk) ProtoMessage() {}

func (x *DataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChunk.ProtoReflect.Descriptor instead.
func (*DataChunk) Descriptor() ([]byte, []int) {
	return file_api_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *DataChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ImportFromRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionToken   string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Digest         string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	SourceEndpoint string                 `protobuf:"bytes,3,opt,name=source_endpoint,json=sourceEndpoint,proto3" json:"source_endpoint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImportFromRequest) Reset() {
	*x = ImportFromRequest{}
	mi := &file_api_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportFromRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportFromRequest) ProtoMessage() {}

func (x *ImportFromRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportFromRequest.ProtoReflect.Descriptor instead.
func (*ImportFromRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ImportFromRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *ImportFromRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ImportFromRequest) GetSourceEndpoint() string {
	if x != nil {
		return x.SourceEndpoint
	}
	return ""
}

type ImportFromResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportFromResponse) Reset() {
	*x = ImportFromResponse{}
	mi := &file_api_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportFromResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportFromResponse) ProtoMessage() {}

func (x *ImportFromResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportFromResponse.ProtoReflect.Descriptor instead.
func (*ImportFromResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ImportFromResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ImportFromResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesRequest) Reset() {
	*x = ListImagesRequest{}
	mi := &file_api_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesRequest) ProtoMessage() {}

func (x *ListImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesRequest.ProtoReflect.Descriptor instead.
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_agent_proto_rawDescGZIP(), []int{6}
}

type ListImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digests       []string               `protobuf:"bytes,1,rep,name=digests,proto3" json:"digests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesResponse) Reset() {
	*x = ListImagesResponse{}
	mi := &file_api_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesResponse) ProtoMessage() {}

func (x *ListImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesResponse.ProtoReflect.Descriptor instead.
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ListImagesResponse) GetDigests() []string {
	if x != nil {
		return x.Digests
	}
	return nil
}

type ResolveTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageRef      string                 `protobuf:"bytes,1,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveTagRequest) Reset() {
	*x = ResolveTagRequest{}
	mi := &file_api_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveTagRequest) ProtoMessage() {}

func (x *ResolveTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveTagRequest.ProtoReflect.Descriptor instead.
func (*ResolveTagRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ResolveTagRequest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

type ResolveTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveTagResponse) Reset() {
	*x = ResolveTagResponse{}
	mi := &file_api_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveTagResponse) ProtoMessage() {}

func (x *ResolveTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveTagResponse.ProtoReflect.Descriptor instead.
func (*ResolveTagResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ResolveTagResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type RemoveImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageRef      string                 `protobuf:"bytes,1,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImageRequest) Reset() {
	*x = RemoveImageRequest{}
	mi := &file_api_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImageRequest) ProtoMessage() {}

func (x *RemoveImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImageRequest.ProtoReflect.Descriptor instead.
func (*RemoveImageRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveImageRequest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

type RemoveImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImageResponse) Reset() {
	*x = RemoveImageResponse{}
	mi := &file_api_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImageResponse) ProtoMessage() {}

func (x *RemoveImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImageResponse.ProtoReflect.Descriptor instead.
func (*RemoveImageResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_agent_proto_rawDescGZIP(), []int{11}
}

var File_api_v1_agent_proto protoreflect.FileDescriptor

const file_api_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x12api/v1/agent.proto\x12\atote.v1\"S\n" +
	"\x14PrepareExportRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\"6\n" +
	"\x15PrepareExportResponse\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x01 \x01(\x03R\tsizeBytes\"9\n" +
	"\x12ExportImageRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\"\x1f\n" +
	"\tDataChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"y\n" +
	"\x11ImportFromRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12'\n" +
	"\x0fsource_endpoint\x18\x03 \x01(\tR\x0esourceEndpoint\"D\n" +
	"\x12ImportFromResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x13\n" +
	"\x11ListImagesRequest\".\n" +
	"\x12ListImagesResponse\x12\x18\n" +
	"\adigests\x18\x01 \x03(\tR\adigests\"0\n" +
	"\x11ResolveTagRequest\x12\x1b\n" +
	"\timage_ref\x18\x01 \x01(\tR\bimageRef\",\n" +
	"\x12ResolveTagResponse\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\"1\n" +
	"\x12RemoveImageRequest\x12\x1b\n" +
	"\timage_ref\x18\x01 \x01(\tR\bimageRef\"\x15\n" +
	"\x13RemoveImageResponse2\xbc\x03\n" +
	"\tToteAgent\x12N\n" +
	"\rPrepareExport\x12\x1d.tote.v1.PrepareExportRequest\x1a\x1e.tote.v1.PrepareExportResponse\x12@\n" +
	"\vExportImage\x12\x1b.tote.v1.ExportImageRequest\x1a\x12.tote.v1.DataChunk0\x01\x12E\n" +
	"\n" +
	"ImportFrom\x12\x1a.tote.v1.ImportFromRequest\x1a\x1b.tote.v1.ImportFromResponse\x12E\n" +
	"\n" +
	"ListImages\x12\x1a.tote.v1.ListImagesRequest\x1a\x1b.tote.v1.ListImagesResponse\x12E\n" +
	"\n" +
	"ResolveTag\x12\x1a.tote.v1.ResolveTagRequest\x1a\x1b.tote.v1.ResolveTagResponse\x12H\n" +
	"\vRemoveImage\x12\x1b.tote.v1.RemoveImageRequest\x1a\x1c.tote.v1.RemoveImageResponseB!Z\x1fgithub.com/ppiankov/tote/api/v1b\x06proto3"

var (
	file_api_v1_agent_proto_rawDescOnce sync.Once
	file_api_v1_agent_proto_rawDescData []byte
)

func file_api_v1_agent_proto_rawDescGZIP() []byte {
	file_api_v1_agent_proto_rawDescOnce.Do(func() {
		file_api_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_agent_proto_rawDesc), len(file_api_v1_agent_proto_rawDesc)))
	})
	return file_api_v1_agent_proto_rawDescData
}

var file_api_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_v1_agent_proto_goTypes = []any{
	(*PrepareExportRequest)(nil),  // 0: tote.v1.PrepareExportRequest
	(*PrepareExportResponse)(nil), // 1: tote.v1.PrepareExportResponse
	(*ExportImageRequest)(nil),    // 2: tote.v1.ExportImageRequest
	(*DataChunk)(nil),             // 3: tote.v1.DataChunk
	(*ImportFromRequest)(nil),     // 4: tote.v1.ImportFromRequest
	(*ImportFromResponse)(nil),    // 5: tote.v1.ImportFromResponse
	(*ListImagesRequest)(nil),     // 6: tote.v1.ListImagesRequest
	(*ListImagesResponse)(nil),    // 7: tote.v1.ListImagesResponse
	(*ResolveTagRequest)(nil),     // 8: tote.v1.ResolveTagRequest
	(*ResolveTagResponse)(nil),    // 9: tote.v1.ResolveTagResponse
	(*RemoveImageRequest)(nil),    // 10: tote.v1.RemoveImageRequest
	(*RemoveImageResponse)(nil),   // 11: tote.v1.RemoveImageResponse
}
var file_api_v1_agent_proto_depIdxs = []int32{
	0,  // 0: tote.v1.ToteAgent.PrepareExport:input_type -> tote.v1.PrepareExportRequest
	2,  // 1: tote.v1.ToteAgent.ExportImage:input_type -> tote.v1.ExportImageRequest
	4,  // 2: tote.v1.ToteAgent.ImportFrom:input_type -> tote.v1.ImportFromRequest
	6,  // 3: tote.v1.ToteAgent.ListImages:input_type -> tote.v1.ListImagesRequest
	8,  // 4: tote.v1.ToteAgent.ResolveTag:input_type -> tote.v1.ResolveTagRequest
	10, // 5: tote.v1.ToteAgent.RemoveImage:input_type -> tote.v1.RemoveImageRequest
	1,  // 6: tote.v1.ToteAgent.PrepareExport:output_type -> tote.v1.PrepareExportResponse
	3,  // 7: tote.v1.ToteAgent.ExportImage:output_type -> tote.v1.DataChunk
	5,  // 8: tote.v1.ToteAgent.ImportFrom:output_type -> tote.v1.ImportFromResponse
	7,  // 9: tote.v1.ToteAgent.ListImages:output_type -> tote.v1.ListImagesResponse
	9,  // 10: tote.v1.ToteAgent.ResolveTag:output_type -> tote.v1.ResolveTagResponse
	11, // 11: tote.v1.ToteAgent.RemoveImage:output_type -> tote.v1.RemoveImageResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_agent_proto_init() }
func file_api_v1_agent_proto_init() {
	if File_api_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_agent_proto_rawDesc), len(file_api_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_agent_proto_goTypes,
		DependencyIndexes: file_api_v1_agent_proto_depIdxs,
		MessageInfos:      file_api_v1_agent_proto_msgTypes,
	}.Build()
	File_api_v1_agent_proto = out.File
	file_api_v1_agent_proto_goTypes = nil
	file_api_v1_agent_proto_depIdxs = nil
}
